/*
 * LedDriverLPF3.h
 *
 * Single-wire, bit-banged LED driver built on top of the LGPTimer driver
 * (LGPTimerLPF3) for CC2340R53 / Low Power F3 devices.
 *
 * The external LED driver IC expects the following pulse timing on its data
 * pin, one pulse per data bit:
 *
 *   Bit '1' : T1H = 550 ns high, then T1L = 350 ns low
 *   Bit '0' : T0H = 230 ns high, then T0L = 670 ns low
 *
 * Each pulse is generated in hardware by a single LGPT channel configured
 * with the LGPTimerLPF3_CH_SET_ON_0_TOGGLE_ON_CMP_PERIODIC channel action:
 * the channel output is set high when the counter is 0, and toggled low
 * again when the counter reaches the configured compare value. The counter
 * is run in one-shot mode (LGPTimerLPF3_CTL_MODE_UP_ONCE) so that exactly
 * one pulse is produced per LedDriverLPF3_setHigh()/LedDriverLPF3_setLow()
 * call, and it restarts from 0 on every call so pulses can be issued
 * back-to-back.
 *
 * Prerequisite configuration:
 *   An LGPTimerLPF3 instance (see ti_drivers_config.c/.h, normally generated
 *   by SysConfig) must already exist at index LEDDRIVER_LGPT_INDEX, with the
 *   pin for channel LEDDRIVER_LGPT_CHANNEL muxed to the GPIO connected to
 *   the LED driver IC's data input. This module only opens that instance
 *   and drives its channel - it does not configure GPIO pin muxing itself.
 *
 * Usage:
 *   1. Configure the LGPT instance/channel/pin as described above.
 *   2. Call LedDriverLPF3_init() once at startup.
 *   3. For every data bit, call LedDriverLPF3_setHigh() (bit '1') or
 *      LedDriverLPF3_setLow() (bit '0'). Each call blocks until its pulse
 *      has been fully generated on the pin.
 *   4. Call LedDriverLPF3_close() to release the timer resource, if needed.
 */

#ifndef LedDriverLPF3__include
#define LedDriverLPF3__include

#include <stdbool.h>
#include <stdint.h>

#include <ti/drivers/timer/LGPTimerLPF3.h>

#ifdef __cplusplus
extern "C" {
#endif

/*! LGPTimerLPF3_config[] index of the LGPT instance used to drive the LED
 *  data pin. Must match a valid entry generated by SysConfig / present in
 *  ti_drivers_config.c.
 */
#ifndef LEDDRIVER_LGPT_INDEX
#define LEDDRIVER_LGPT_INDEX 0
#endif

/*! LGPT channel number whose output pin is wired to the LED driver's data
 *  input.
 */
#ifndef LEDDRIVER_LGPT_CHANNEL
#define LEDDRIVER_LGPT_CHANNEL LGPTimerLPF3_CH_NO_0
#endif

/*! Timer counter clock (CLKSVT) frequency in Hz feeding the LGPT peripheral,
 *  used to convert the LED driver's nanosecond timing into timer ticks.
 *  Must match the actual system clock frequency when the LGPT prescaler is
 *  left at its default divide-by-1 setting.
 */
#ifndef LEDDRIVER_TIMER_CLOCK_FREQ
#define LEDDRIVER_TIMER_CLOCK_FREQ 48000000UL
#endif

/*!
 *  @brief  Opens and configures the LGPTimer instance/channel used to drive
 *          the external LED driver's data pin, and idles the pin low.
 *          Must be called once before LedDriverLPF3_setHigh() or
 *          LedDriverLPF3_setLow().
 *
 *  @return true on success, false if the LGPTimer instance could not be
 *          opened (for example if it is already in use).
 */
bool LedDriverLPF3_init(void);

/*!
 *  @brief  Closes the LGPTimer instance opened by LedDriverLPF3_init() and
 *          releases the underlying timer resource.
 *
 *  @pre    LedDriverLPF3_init() has to be called first.
 */
void LedDriverLPF3_close(void);

/*!
 *  @brief  Generates one bit '1' pulse on the LED driver data pin: high for
 *          T1H (550 ns), then low for T1L (350 ns). Blocks until the pulse
 *          has completed.
 *
 *  @pre    LedDriverLPF3_init() has to be called first.
 */
void LedDriverLPF3_setHigh(void);

/*!
 *  @brief  Generates one bit '0' pulse on the LED driver data pin: high for
 *          T0H (230 ns), then low for T0L (670 ns). Blocks until the pulse
 *          has completed.
 *
 *  @pre    LedDriverLPF3_init() has to be called first.
 */
void LedDriverLPF3_setLow(void);

#ifdef __cplusplus
}
#endif

#endif /* LedDriverLPF3__include */
